language: cpp
compiler:
  - clang
  - gcc
dist: trusty
sudo: required
git:
  submodules: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libvulkan-dev xorg-dev libglm-dev libassimp-dev
script:
  - mkdir build && cd build
  - cmake ..
  - make