version: '{build}'

#branches:
#  only:
#- master

os: Visual Studio 2015

platform:
  - x64
 #- Win32

configuration:
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - choco install graphviz.portable 
  - choco install doxygen.portable
  - cmd: curl --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.0.61.1/windows/VulkanSDK-1.0.61.1-Installer.exe
  - cmd: .\VulkanSDK.exe /S

environment:
  VULKAN_SDK: "C:/VulkanSDK/1.0.61.1"
  
clone_folder: C:\libsga

before_build:
  - cmd: cd C:\libsga
  - cmd: md build
  - cmd: cd build
  #- cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  #- cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% ..

build:
  project: C:\libsga\build\libsga.sln
  parallel: true
  verbosity: minimal

after_build:
  - cmd: dir C:\libsga\build
  - cmd: dir C:\libsga\build\Release
  - cmd: msbuild "C:\libsga\build\release.vcxproj" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: dir C:\libsga\build
  - cmd: dir C:\libsga\build\Release
  - cmd: dir C:\libsga\
  - cmd: dir C:\libsga\build\release-windows\libsga-*

artifacts:
  - path: build\libsga.sln
  - path: build\release.vcxproj
  - path: 'build\release-windows\*.zip'

notifications:
- provider: Email
  to:
  - rafalcieslak256+sgabuilds@gmail.com
  subject: SGA appveyor build {{buildVersion}} - {{status}}
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
