version: 2
jobs:
  build:
    working_directory: ~/libsga
    docker:
      - image: rafalcieslak/libsga-build-base:1.2
    steps:
      - checkout
      - run:
          name: 'Run cmake'
          command: |
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
      - run:
          name: 'Compile libsga'
          command: |
            cd build
            make -j2
      - run:
          name: 'Prepare release'
          command: |
            cd build
            make release -j2
      - add_ssh_keys
      - run:
          name: 'Upload releases'
          command: |
            scp -oStrictHostKeyChecking=no ~/libsga/build/release-linux/*.tar.gz circleci-builds@cielak.org:/www/libsga-builds/.